### ISSUE TITLE
Performance tweaks

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#1236]
- [x] improve waitUntil/ sleep
- [x] let open Browser context without url to reduce time taken for browser spawning #1235 
- [x] Clean up write (recheck on delay used, wait for element to be writable seems redundant)
- [x] Consolidate Text based search to avoid to and fro checks #1237
- [x] Check need for reconnect in closeBrowser
- [x] Try caching selector methods in browser
- [ ] Wait for element to be actionable before performing any action #630 
- [ ] Make waitForNavigation default to false expect for navigation actions like goto, reload, openTab with url after doing the above step
